### ISSUE TITLE
SampleScene scene contains Projector For LWRP components but the current render pipeline asset does not have ProjectorRendererFeature

### ISSUE THREAD

**Issue by ybasori** [nyahoon-games/ProjectorForLWRP#6]
I did change the renderer list but it keeps telling me "SampleScene scene contains Projector For LWRP components but the current render pipeline asset does not have ProjectorRendererFeature"

tell me where I did wrong?

![image](https://user-images.githubusercontent.com/18370818/200144330-231dacae-d83f-48b3-8193-f33317502e75.png)

![image](https://user-images.githubusercontent.com/18370818/200144371-1912570e-df4a-40ea-acde-90d3009566f6.png)

**Comment by takaokato** [comment]
Hi, Graphics settings can be overwritten by Quality settings. Please check your current quality settings.

**Comment by ybasori** [comment]
> Hi, Graphics settings can be overwritten by Quality settings. Please check your current quality settings.

thanks for the reply. 

So, i'm new in unity, sorry for asking stupid question.

which one is quality settings?

**Comment by ybasori** [comment]
> Hi, Graphics settings can be overwritten by Quality settings. Please check your current quality settings.

is it this one?

![image](https://user-images.githubusercontent.com/18370818/200215313-441c6df7-d182-4f6a-a1e2-750d3c9406e7.png)

**Comment by takaokato** [comment]
Yes, it is. The current active quality level is High Fidelity which should work fine. However, It seems like you have another error in Console window now. What is that?

**Comment by ybasori** [comment]
> Yes, it is. The current active quality level is High Fidelity which should work fine. However, It seems like you have another error in Console window now. What is that?

so I should ignore the current error? okay then, thanks

the other error is not come from the package, it's from other package

**Comment by takaokato** [comment]
No, if you still have the error, there might be something wrong with the settings. Can you see a spot light and a shadow on the plane?

**Comment by ybasori** [comment]
you mean this one?

![image](https://user-images.githubusercontent.com/18370818/200300145-b4b8fa53-4bf9-489d-8c28-ae6aca27014e.png)

**Comment by takaokato** [comment]
Ah, I misunderstood about the issue. I thought the error was logged from ProjectorRendererFeature but it was from PostProcessBuildCheck. Please ignore this error. I will fix this issue. Thanks

**Comment by ybasori** [comment]
thanks for the fix
